/**
 * Corridor buffer engine parity harness.
 *
 * Proves the TypeScript corridor geometry is equivalent to GEOS (the
 * reference engine behind QGIS and PostGIS) on deterministic fixtures.
 * Golden polygons are generated by scripts/golden_buffers.py with
 * shapely 2.x: round joins (quad_segs=8), flat caps.
 *
 * This closes the roadmap's deferred "engine swap needs golden-file
 * parity proof" item -- with GEOS as reference rather than turf.js,
 * because cadastral corridors are planar grid-meter geometry (turf
 * buffers geodesically in degrees, the wrong model for projected CRS).
 */
import * as assert from "assert";
// esbuild bundles the JSON fixture inline, so the test binary is self-contained.
import golden from "./fixtures/buffer-golden.json";

import {
  generateCorridorBuffers,
  pointToSegmentDistance,
  ringArea,
} from "../src/core/buffer-engine";
import { SurveyVector, SurveyPoint } from "../src/types/spatial";

interface GoldenBuffer {
  halfWidthM: number;
  exteriorRing: [number, number][];
  areaSqM: number;
  perimeterM: number;
}
interface GoldenFixture {
  centerline: [number, number][];
  buffers: GoldenBuffer[];
}

/* ---------- helpers ---------- */

function makeVector(id: string, category: "road" | "water", pts: [number, number][]): SurveyVector {
  return {
    id,
    code: category === "road" ? "RD-CL" : category === "water" ? "RIV" : "BND",
    name: `fixture-${id}`,
    category,
    layer: "fixtures",
    points: pts.map(([e, n], i) => ({
      id: `${id}-p${i}`,
      easting: e,
      northing: n,
      elevation: 0,
      rawCode: "",
      category,
      description: "",
    })),
    isClosed: false,
    color: "#000",
    lineType: "solid",
    lineWidth: 1,
  };
}

function makePoint(e: number, n: number, category: SurveyPoint["category"]): SurveyPoint {
  return {
    id: `pt-${e}-${n}`,
    easting: e,
    northing: n,
    elevation: 0,
    rawCode: "",
    category,
    description: "",
  };
}

/** Min distance from a point to a closed/open ring's boundary. */
function distToRing(px: number, py: number, ring: [number, number][]): number {
  let best = Infinity;
  for (let i = 0; i < ring.length - 1; i++) {
    best = Math.min(
      best,
      pointToSegmentDistance(px, py, ring[i][0], ring[i][1], ring[i + 1][0], ring[i + 1][1])
    );
  }
  return best;
}

/** Proper segment-segment intersection (excluding collinear touch). */
function segsIntersect(a: [number, number][], b: [number, number][]): boolean {
  const o = (p: [number, number], q: [number, number], r: [number, number]) => {
    const v = (q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0]);
    return v > 1e-9 ? 1 : v < -1e-9 ? -1 : 0;
  };
  const onSeg = (p: [number, number], q: [number, number], r: [number, number]) =>
    Math.min(p[0], r[0]) - 1e-9 <= q[0] && q[0] <= Math.max(p[0], r[0]) + 1e-9 &&
    Math.min(p[1], r[1]) - 1e-9 <= q[1] && q[1] <= Math.max(p[1], r[1]) + 1e-9;
  const [p1, p2] = a;
  const [p3, p4] = b;
  const d1 = o(p3, p4, p1), d2 = o(p3, p4, p2), d3 = o(p1, p2, p3), d4 = o(p1, p2, p4);
  if (((d1 > 0 && d2 < 0) || (d1 < 0 && d2 > 0)) && ((d3 > 0 && d4 < 0) || (d3 < 0 && d4 > 0)))
    return true;
  if (d1 === 0 && onSeg(p3, p1, p4)) return true;
  if (d2 === 0 && onSeg(p3, p2, p4)) return true;
  if (d3 === 0 && onSeg(p1, p3, p2)) return true;
  if (d4 === 0 && onSeg(p1, p4, p2)) return true;
  return false;
}

/** A ring is simple when no two non-adjacent segments cross. */
function isSimpleRing(ring: [number, number][]): boolean {
  const n = ring.length - 1; // last vertex repeats the first
  if (n < 4) return true;
  for (let i = 0; i < n; i++) {
    for (let j = i + 2; j < n; j++) {
      if (i === 0 && j === n - 1) continue; // first & last segments share a vertex
      if (segsIntersect([ring[i], ring[i + 1]], [ring[j], ring[j + 1]])) return false;
    }
  }
  return true;
}

/**
 * Boundary agreement tolerance (metres). With quad_segs=8 the arc chord
 * sagitta at a 15 m half-width is r*(1-cos(5.625 deg)) ~= 0.072 m; vertex
 * placement may be rotated relative to GEOS, so allow 0.10 m.
 */
const BOUNDARY_TOL_M = 0.1;
/** Relative area tolerance. Same arc density makes this near-exact (<0.1%). */
const AREA_TOL_REL = 0.005;

/* ---------- 1. Parity vs GEOS golden files ---------- */
{
  let checked = 0;
  for (const [name, fx] of Object.entries(golden.fixtures)) {
    for (const gb of fx.buffers) {
      // hw 7.5 m -> 15 m road reserve; hw 15 m -> 30 m riparian corridor.
      const category = gb.halfWidthM === 7.5 ? "road" : "water";
      const roadW = category === "road" ? gb.halfWidthM * 2 : 15.0;
      const ripW = category === "water" ? gb.halfWidthM * 2 : 30.0;
      const [buf] = generateCorridorBuffers(
        [makeVector(name, category, fx.centerline)],
        [],
        roadW,
        ripW
      );
      assert.ok(buf, `${name}@${gb.halfWidthM}: engine returned no buffer`);

      const ours = buf.polygon;
      assert.strictEqual(
        ours[0][0], ours[ours.length - 1][0],
        `${name}@${gb.halfWidthM}: ring not closed (E)`
      );
      assert.strictEqual(
        ours[0][1], ours[ours.length - 1][1],
        `${name}@${gb.halfWidthM}: ring not closed (N)`
      );
      assert.ok(
        isSimpleRing(ours),
        `${name}@${gb.halfWidthM}: corridor ring self-intersects`
      );

      // Area parity vs GEOS.
      const area = ringArea(ours);
      const relDiff = Math.abs(area - gb.areaSqM) / gb.areaSqM;
      assert.ok(
        relDiff <= AREA_TOL_REL,
        `${name}@${gb.halfWidthM}: area ${area.toFixed(2)} vs GEOS ${gb.areaSqM.toFixed(2)} ` +
          `(rel diff ${(relDiff * 100).toFixed(3)}% > ${AREA_TOL_REL * 100}%)`
      );

      // Boundary agreement both ways (robust to arc vertex placement).
      for (const [x, y] of ours) {
        const d = distToRing(x, y, gb.exteriorRing);
        assert.ok(
          d <= BOUNDARY_TOL_M,
          `${name}@${gb.halfWidthM}: our vertex (${x},${y}) is ${d.toFixed(4)} m from GEOS boundary`
        );
      }
      for (const [x, y] of gb.exteriorRing) {
        const d = distToRing(x, y, ours);
        assert.ok(
          d <= BOUNDARY_TOL_M,
          `${name}@${gb.halfWidthM}: GEOS vertex (${x},${y}) is ${d.toFixed(4)} m from our boundary`
        );
      }
      checked++;
    }
  }
  console.log(`PASS: GEOS parity on ${checked} fixture buffers (area + boundary + simplicity)`);
}

/* ---------- 2. Straight corridor: exact rectangle, area = L x W ---------- */
{
  const [buf] = generateCorridorBuffers(
    [makeVector("straight", "road", [[1000, 2000], [1200, 2000]])],
    [],
    15,
    30
  );
  const area = ringArea(buf.polygon);
  assert.ok(
    Math.abs(area - 3000) < 1e-6,
    `straight corridor area ${area} != 200 x 15 = 3000`
  );
  assert.strictEqual(buf.areaSqM, 3000);
  console.log("PASS: straight corridor is an exact rectangle (L x W register area)");
}

/* ---------- 3. Degenerate input: duplicate + collinear vertices ---------- */
{
  const [buf] = generateCorridorBuffers(
    [makeVector("degen", "road", [[1000, 2000], [1100, 2000], [1100, 2000], [1200, 2000]])],
    [],
    15,
    30
  );
  const area = ringArea(buf.polygon);
  assert.ok(
    Math.abs(area - 3000) < 1e-6,
    `degenerate corridor area ${area} != 3000 (duplicate vertex not removed)`
  );
  assert.ok(isSimpleRing(buf.polygon), "degenerate corridor ring not simple");
  console.log("PASS: duplicate/collinear vertices handled without geometry corruption");
}

/* ---------- 4. Round join actually widens at a bend (v1 defect regression) ---------- */
{
  // 90-degree bend: v1's independent per-segment offsets left a wedge gap
  // at the outer corner. v2's round join must cover it.
  const [buf] = generateCorridorBuffers(
    [makeVector("bend", "road", [[1000, 2000], [1100, 2000], [1100, 2120]])],
    [],
    15,
    30
  );
  const area = ringArea(buf.polygon);
  // GEOS reference for this geometry: 3287.65 m^2 (golden fixture right_angle).
  const ref = golden.fixtures.right_angle.buffers[0].areaSqM;
  assert.ok(
    Math.abs(area - ref) / ref <= AREA_TOL_REL,
    `bend area ${area.toFixed(2)} vs GEOS ${ref.toFixed(2)}`
  );
  // The old per-segment polygon (two strips) would compute 220*15 = 3300
  // minus a wedge gap; assert we are within tolerance of GEOS, not L*W.
  assert.ok(isSimpleRing(buf.polygon), "bend corridor ring not simple");
  console.log(`PASS: round joins cover bend wedges (area ${area.toFixed(2)} ~= GEOS ${ref.toFixed(2)})`);
}

/* ---------- 5. Encroachment detection still wired ---------- */
{
  const vec = makeVector("enc", "road", [[1000, 2000], [1200, 2000]]);
  const inside = makePoint(1100, 2003, "building"); // 3 m from centerline, inside 7.5 m
  const outside = makePoint(1100, 2030, "building"); // 30 m away, outside
  const [hit] = generateCorridorBuffers([vec], [inside], 15, 30);
  assert.strictEqual(hit.encroachmentDetected, true, "inside building not flagged");
  const [miss] = generateCorridorBuffers([vec], [outside], 15, 30);
  assert.strictEqual(miss.encroachmentDetected, false, "outside building falsely flagged");
  console.log("PASS: encroachment detection true/false both correct");
}

/* ---------- 6. Non-corridor categories skipped; empty input safe ---------- */
{
  const none = generateCorridorBuffers(
    [makeVector("bnd", "boundary", [[0, 0], [10, 10]])],
    [],
    15,
    30
  );
  assert.strictEqual(none.length, 0, "boundary vector should not buffer");
  const empty = generateCorridorBuffers([], [], 15, 30);
  assert.strictEqual(empty.length, 0);
  const single = generateCorridorBuffers(
    [makeVector("one", "road", [[5, 5]])],
    [],
    15,
    30
  );
  assert.strictEqual(single.length, 0, "single-point vector should not buffer");
  console.log("PASS: category filter and empty/degenerate inputs safe");
}

console.log("ALL BUFFER PARITY TESTS PASSED");
